Traceback (most recent call last):
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.datasets import fetch_california_housing

X, y = fetch_california_housing(return_X_y=True, as_frame=True)
X
------------------

----- stderr -----
/home/runner/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/sklearn/datasets/_base.py:1472: UserWarning: Retry downloading from url: https://ndownloader.figshare.com/files/5976036
  warnings.warn(f"Retry downloading from url: {remote.url}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m fetch_california_housing
[0;32m----> 3[0m X, y [38;5;241m=[39m [43mfetch_california_housing[49m[43m([49m[43mreturn_X_y[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mas_frame[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m      4[0m X

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:213[0m, in [0;36mvalidate_params.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    207[0m [38;5;28;01mtry[39;00m:
[1;32m    208[0m     [38;5;28;01mwith[39;00m config_context(
[1;32m    209[0m         skip_parameter_validation[38;5;241m=[39m(
[1;32m    210[0m             prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m    211[0m         )
[1;32m    212[0m     ):
[0;32m--> 213[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    214[0m [38;5;28;01mexcept[39;00m InvalidParameterError [38;5;28;01mas[39;00m e:
[1;32m    215[0m     [38;5;66;03m# When the function is just a wrapper around an estimator, we allow[39;00m
[1;32m    216[0m     [38;5;66;03m# the function to delegate validation to the estimator, but we replace[39;00m
[1;32m    217[0m     [38;5;66;03m# the name of the estimator by the name of the function in the error[39;00m
[1;32m    218[0m     [38;5;66;03m# message to avoid confusion.[39;00m
[1;32m    219[0m     msg [38;5;241m=[39m re[38;5;241m.[39msub(
[1;32m    220[0m         [38;5;124mr[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;124m\[39m[38;5;124mw+ must be[39m[38;5;124m"[39m,
[1;32m    221[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m,
[1;32m    222[0m         [38;5;28mstr[39m(e),
[1;32m    223[0m     )

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/sklearn/datasets/_california_housing.py:177[0m, in [0;36mfetch_california_housing[0;34m(data_home, download_if_missing, return_X_y, as_frame, n_retries, delay)[0m
[1;32m    171[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m"[39m[38;5;124mData not found and `download_if_missing` is False[39m[38;5;124m"[39m)
[1;32m    173[0m logger[38;5;241m.[39minfo(
[1;32m    174[0m     [38;5;124m"[39m[38;5;124mDownloading Cal. housing from [39m[38;5;132;01m{}[39;00m[38;5;124m to [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(ARCHIVE[38;5;241m.[39murl, data_home)
[1;32m    175[0m )
[0;32m--> 177[0m archive_path [38;5;241m=[39m [43m_fetch_remote[49m[43m([49m
[1;32m    178[0m [43m    [49m[43mARCHIVE[49m[43m,[49m
[1;32m    179[0m [43m    [49m[43mdirname[49m[38;5;241;43m=[39;49m[43mdata_home[49m[43m,[49m
[1;32m    180[0m [43m    [49m[43mn_retries[49m[38;5;241;43m=[39;49m[43mn_retries[49m[43m,[49m
[1;32m    181[0m [43m    [49m[43mdelay[49m[38;5;241;43m=[39;49m[43mdelay[49m[43m,[49m
[1;32m    182[0m [43m[49m[43m)[49m
[1;32m    184[0m [38;5;28;01mwith[39;00m tarfile[38;5;241m.[39mopen(mode[38;5;241m=[39m[38;5;124m"[39m[38;5;124mr:gz[39m[38;5;124m"[39m, name[38;5;241m=[39marchive_path) [38;5;28;01mas[39;00m f:
[1;32m    185[0m     cal_housing [38;5;241m=[39m np[38;5;241m.[39mloadtxt(
[1;32m    186[0m         f[38;5;241m.[39mextractfile([38;5;124m"[39m[38;5;124mCaliforniaHousing/cal_housing.data[39m[38;5;124m"[39m), delimiter[38;5;241m=[39m[38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m
[1;32m    187[0m     )

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/site-packages/sklearn/datasets/_base.py:1466[0m, in [0;36m_fetch_remote[0;34m(remote, dirname, n_retries, delay)[0m
[1;32m   1464[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[1;32m   1465[0m     [38;5;28;01mtry[39;00m:
[0;32m-> 1466[0m         [43murlretrieve[49m[43m([49m[43mremote[49m[38;5;241;43m.[39;49m[43murl[49m[43m,[49m[43m [49m[43mfile_path[49m[43m)[49m
[1;32m   1467[0m         [38;5;28;01mbreak[39;00m
[1;32m   1468[0m     [38;5;28;01mexcept[39;00m (URLError, [38;5;167;01mTimeoutError[39;00m):

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:240[0m, in [0;36murlretrieve[0;34m(url, filename, reporthook, data)[0m
[1;32m    223[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    224[0m [38;5;124;03mRetrieve a URL into a temporary location on disk.[39;00m
[1;32m    225[0m 
[0;32m   (...)[0m
[1;32m    236[0m [38;5;124;03mdata file as well as the resulting HTTPMessage object.[39;00m
[1;32m    237[0m [38;5;124;03m"""[39;00m
[1;32m    238[0m url_type, path [38;5;241m=[39m _splittype(url)
[0;32m--> 240[0m [38;5;28;01mwith[39;00m contextlib[38;5;241m.[39mclosing([43murlopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m) [38;5;28;01mas[39;00m fp:
[1;32m    241[0m     headers [38;5;241m=[39m fp[38;5;241m.[39minfo()
[1;32m    243[0m     [38;5;66;03m# Just return the local path and the "headers" for file://[39;00m
[1;32m    244[0m     [38;5;66;03m# URLs. No sense in performing a copy unless requested.[39;00m

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:215[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    213[0m [38;5;28;01melse[39;00m:
[1;32m    214[0m     opener [38;5;241m=[39m _opener
[0;32m--> 215[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:521[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    519[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[1;32m    520[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[0;32m--> 521[0m     response [38;5;241m=[39m [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[1;32m    523[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:630[0m, in [0;36mHTTPErrorProcessor.http_response[0;34m(self, request, response)[0m
[1;32m    627[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[1;32m    628[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[1;32m    629[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[0;32m--> 630[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43merror[49m[43m([49m
[1;32m    631[0m [43m        [49m[38;5;124;43m'[39;49m[38;5;124;43mhttp[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[1;32m    633[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:559[0m, in [0;36mOpenerDirector.error[0;34m(self, proto, *args)[0m
[1;32m    557[0m [38;5;28;01mif[39;00m http_err:
[1;32m    558[0m     args [38;5;241m=[39m ([38;5;28mdict[39m, [38;5;124m'[39m[38;5;124mdefault[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mhttp_error_default[39m[38;5;124m'[39m) [38;5;241m+[39m orig_args
[0;32m--> 559[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:492[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    490[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    491[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 492[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    493[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    494[0m         [38;5;28;01mreturn[39;00m result

File [0;32m~/work/traces-sklearn/traces-sklearn/.pixi/envs/docs/lib/python3.12/urllib/request.py:639[0m, in [0;36mHTTPDefaultErrorHandler.http_error_default[0;34m(self, req, fp, code, msg, hdrs)[0m
[1;32m    638[0m [38;5;28;01mdef[39;00m [38;5;21mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[0;32m--> 639[0m     [38;5;28;01mraise[39;00m HTTPError(req[38;5;241m.[39mfull_url, code, msg, hdrs, fp)

[0;31mHTTPError[0m: HTTP Error 403: Forbidden

